In [7]:
# importing dependencies
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [ ]:
pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in e:\machine learning projects\.myvenv\lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.5.9-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in e:\machine learning projects\.myvenv\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   --------------------------------- ------ 1.3/1.6 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 8.9 MB/s  0:00:00
Downloading regex-2026.5.9-cp314-cp314-win_amd64.whl (280 kB)
Downloading click-8.4.1-py3-none-any.whl (116 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, click, nltk

   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------- ----------------------------- 1/4 [regex]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ---------------------------------------- 4/4 [nltk]

Successfully installed click-8.4.1 nltk-3.9.4 regex-2026.5.9 tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import nltk

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shriv\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [16]:
stop_wrods = stopwords.words('english')
print(stop_wrods)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [17]:
# Data preprccesing
news_data = pd.read_csv("E:\\Machine Learning projects\\data\\fake_news_prediction.csv")

In [18]:
news_data.head()

   id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [19]:
news_data.shape

(20800, 5)

In [21]:
news_data.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [22]:
# here we are replacing with null string
news_data = news_data.fillna('')

In [59]:
# merge the author name and news title 
news_data['content'] = news_data['author']+' '+news_data['title']

In [60]:
news_data.head()

   id  ...                                            content
0   0  ...  Darrell Lucus House Dem Aide: We Didn’t Even S...
1   1  ...  Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2   2  ...  Consortiumnews.com Why the Truth Might Get You...
3   3  ...  Jessica Purkiss 15 Civilians Killed In Single ...
4   4  ...  Howard Portnoy Iranian woman jailed for fictio...

[5 rows x 6 columns]

In [61]:
X = news_data['content']
Y = news_data['label']

In [62]:
print(X)

0        Darrell Lucus House Dem Aide: We Didn’t Even S...
1        Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2        Consortiumnews.com Why the Truth Might Get You...
3        Jessica Purkiss 15 Civilians Killed In Single ...
4        Howard Portnoy Iranian woman jailed for fictio...
                               ...
20795    Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...
20796    Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma...
20797    Michael J. de la Merced and Rachel Abrams Macy...
20798    Alex Ansary NATO, Russia To Hold Parallel Exer...
20799              David Swanson What Keeps the F-35 Alive
Name: content, Length: 20800, dtype: str

In [63]:
# stemming --> it is the proccess of reducing the word to its root word

In [64]:
port_stem = PorterStemmer()

In [66]:
def steaming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [67]:
news_data['content'] = news_data['content'].apply(steaming)

In [68]:
news_data['content']

0        darrel lucu hous dem aid even see comey letter...
1        daniel j flynn flynn hillari clinton big woman...
2                   consortiumnew com truth might get fire
3        jessica purkiss civilian kill singl us airstri...
4        howard portnoy iranian woman jail fiction unpu...
                               ...
20795    jerom hudson rapper trump poster child white s...
20796    benjamin hoffman n f l playoff schedul matchup...
20797    michael j de la merc rachel abram maci said re...
20798    alex ansari nato russia hold parallel exercis ...
20799                            david swanson keep f aliv
Name: content, Length: 20800, dtype: str

In [69]:
x = news_data['content'].values
y = news_data['label'].values

In [70]:
print(x,y)

<StringArray>
[                                              'darrel lucu hous dem aid even see comey letter jason chaffetz tweet',
                                                    'daniel j flynn flynn hillari clinton big woman campu breitbart',
                                                                            'consortiumnew com truth might get fire',
                                                          'jessica purkiss civilian kill singl us airstrik identifi',
                              'howard portnoy iranian woman jail fiction unpublish stori woman stone death adulteri',
 'daniel nussbaum jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
                                 'life life luxuri elton john favorit shark pictur stare long transcontinent flight',
                               'alissa j rubin beno hamon win french socialist parti presidenti nomin new york time',
                                        'excerpt draft script donald trump q ampa black church pastor new york time',
                      'megan twohey scott shane back channel plan ukrain russia courtesi trump associ new york time',
 ...
                                 'adam shaw nikki haley blast u n human right offic unfair bia israel latest report',
                                       'daniel greenfield lawyer kept hillari campaign chief jail doj hillari probe',
                                                 'john hayward jakarta bomb kill three polic offic link islam state',
                                                 'robert rich idiot destroy trump hollywood star get exactli deserv',
                                                   'lee stranahan trump putin smart retali obama sanction breitbart',
                                                            'jerom hudson rapper trump poster child white supremaci',
                                                  'benjamin hoffman n f l playoff schedul matchup odd new york time',
                       'michael j de la merc rachel abram maci said receiv takeov approach hudson bay new york time',
                                                              'alex ansari nato russia hold parallel exercis balkan',
                                                                                         'david swanson keep f aliv']
Length: 20800, dtype: str [1 0 1 ... 0 1 1]

In [71]:
print(x.shape,y.shape)

(20800,) (20800,)

In [72]:
vectorizer = TfidfVectorizer()

In [73]:
vectorizer.fit(x)

TfidfVectorizer()

In [74]:
x = vectorizer.transform(x)

In [75]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 210687 stored elements and shape (20800, 17128)>
  Coords	Values
  (0, 267)	0.2701012497770876
  (0, 2483)	0.36765196867972083
  (0, 2959)	0.24684501285337127
  (0, 3600)	0.3598939188262558
  (0, 3792)	0.27053324808454915
  (0, 4973)	0.23331696690935097
  (0, 7005)	0.2187416908935914
  (0, 7692)	0.24785219520671598
  (0, 8630)	0.2921251408704368
  (0, 8909)	0.36359638063260746
  (0, 13473)	0.2565896679337956
  (0, 15686)	0.2848506356272864
  (1, 1497)	0.2939891562094648
  (1, 1894)	0.15521974226349364
  (1, 2223)	0.3827320386859759
  (1, 2813)	0.19094574062359204
  (1, 3568)	0.26373768806048464
  (1, 5503)	0.7143299355715573
  (1, 6816)	0.1904660198296849
  (1, 16799)	0.30071745655510157
  (2, 2943)	0.3179886800654691
  (2, 3103)	0.46097489583229645
  (2, 5389)	0.3866530551182615
  (2, 5968)	0.3474613386728292
  (2, 9620)	0.49351492943649944
  :	:
  (20797, 3643)	0.2115550061362374
  (20797, 7042)	0.21799048897828685
  (20797, 8364)	0.22322585870464115
  (20797, 8988)	0.36160868928090795
  (20797, 9518)	0.29542040034203126
  (20797, 9588)	0.17455348025522197
  (20797, 10306)	0.08038079000566466
  (20797, 12138)	0.24778257724396505
  (20797, 12344)	0.27263457663336677
  (20797, 13122)	0.24825263521976057
  (20797, 14967)	0.3115945315488075
  (20797, 15295)	0.08159261204402356
  (20797, 16996)	0.08315655906109998
  (20798, 350)	0.2844693781907258
  (20798, 588)	0.3112141524638974
  (20798, 1125)	0.4460515589182237
  (20798, 5032)	0.40837014502395297
  (20798, 6889)	0.3249628569429943
  (20798, 10177)	0.31924963701870285
  (20798, 11052)	0.4460515589182237
  (20798, 13046)	0.2236326748827061
  (20799, 377)	0.5677577267055112
  (20799, 3623)	0.37927626273066584
  (20799, 8036)	0.45983893273780013
  (20799, 14852)	0.5677577267055112

In [ ]:
# spam mail --> kaggle